# Generated by Django 5.1.15 on 2026-07-07 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Used as subdomain: {slug}.tarxemo.com', max_length=80, unique=True)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='tenants/favicons/')),
                ('plan', models.CharField(choices=[('TRIAL', 'Trial'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('ENTERPRISE', 'Enterprise')], default='TRIAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRIAL', 'Trial'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Setup')], default='PENDING', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification Failed'), ('ACTIVE', 'Active')], default='PENDING', max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_provisioned', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_domain',
            },
        ),
        migrations.CreateModel(
            name='TenantTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#E8580A', max_length=20)),
                ('primary_color_dark', models.CharField(default='#FF7A2F', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('accent_color', models.CharField(default='#1A1A2E', max_length=20)),
                ('background_color', models.CharField(default='#F8F9FA', max_length=20)),
                ('background_dark', models.CharField(default='#0D0D1A', max_length=20)),
                ('text_color', models.CharField(default='#1A1A2E', max_length=20)),
                ('text_color_dark', models.CharField(default='#E2E8F0', max_length=20)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('font_family_url', models.CharField(default='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap', max_length=300)),
                ('heading_font_family', models.CharField(default='Inter', max_length=100)),
                ('border_radius', models.CharField(default='12px', max_length=20)),
                ('button_border_radius', models.CharField(default='8px', max_length=20)),
                ('custom_css', models.TextField(blank=True, help_text="Raw CSS injected into the tenant's frontend (advanced)")),
                ('default_dark_mode', models.BooleanField(default=False)),
                ('allow_dark_mode_toggle', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_theme',
            },
        ),
    ]
