# Generated by Django 5.1.15 on 2026-07-08 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('TENANT_ADMIN', 'Tenant Admin'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('FINANCE_OFFICER', 'Finance Officer'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer'), ('VIEWER', 'Viewer')], default='OPERATIONS_MANAGER', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants_membership',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
