# Generated by Django 5.1.15 on 2026-07-07 14:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('as_of', models.DateTimeField(help_text='The point in time being viewed')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chrono_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chrono_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChronoSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('snapshot_at', models.DateTimeField(db_index=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system', models.BooleanField(default=False, help_text='True for auto-generated daily snapshots')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chrono_snapshot',
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RESTORE', 'Restore')], db_index=True, max_length=10)),
                ('state_snapshot', models.JSONField(default=dict)),
                ('diff', models.JSONField(default=dict)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('extra_metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chrono_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chrono_audit_logs', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'chrono_audit_log',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['content_type', 'object_id', 'timestamp'], name='chrono_audi_content_e9d878_idx'), models.Index(fields=['tenant_id', 'timestamp'], name='chrono_audi_tenant__e36320_idx'), models.Index(fields=['actor', 'timestamp'], name='chrono_audi_actor_i_bf8a43_idx')],
            },
        ),
    ]
