# Generated by Django 5.1.15 on 2026-07-08 17:35

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default=apps.authentication.models.generate_6_digit_otp, max_length=6),
        ),
    ]
