# Generated by Django 5.1.15 on 2026-07-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, default='CUSTOMER', max_length=30),
        ),
    ]
